apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-webapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/razbd0123-cmd/my-kubernetes-manush.git
    targetRevision: master
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: my-webapp

  syncPolicy:
    automated:
      prune: true        # מוחק משאבים שהוסרו מגיט
      selfHeal: true     # מתקן שינויים ידניים אוטומטית
    syncOptions:
      - CreateNamespace=true
